accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('profile/<pk>/', views.ProfileDetails.as_view(), name='profile')
]

api/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'


urlpatterns = [
    path('all_posts/', views.AllPosts.as_view(), name='allposts'),
    path('example/', views.Example.as_view(), name='example'),
    # path('login/', obtain_auth_token, name='login'),
    # path('user/', views.LoginView.as_view(), name='user'),
    path('jwttoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwttoken/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('xxxx/', views.LoginView.as_view(), name='xxx')

]

groups/urls.py
from django.urls import path

from . import views
from posts import views as postviews

app_name = 'groups'

urlpatterns = [
    path('<slug>/', views.SingleGroup.as_view(), name='single'),
    path('<int:pk>/posts/', postviews.GroupPosts, name='groupposts'),
    path('', views.ListGroups.as_view(), name='all'),
    path('new', views.CreateGroup.as_view(), name='create'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave')
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('api/', include('api.urls', namespace='api'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django import template
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.text import slugify
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def create_default_group(self):
        self.name = "Public"
        self.description = "Public Group"
        self.save()

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(
        Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='usergroups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.views.generic import CreateView, TemplateView, DetailView, ListView, RedirectView

from .models import Group, GroupMember
from django.contrib.auth import get_user_model
User = get_user_model()


class CreateGroup(LoginRequiredMixin, CreateView):
    model = Group
    fields = ('name', 'description')


class SingleGroup(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'groups/group_detail.html'


class ListGroups(LoginRequiredMixin, ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'Warning already a member!')

        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            )
        except:
            messages.warning(self.request, 'You are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        
        {% block pregroup %}
        {% endblock pregroup %}

        {% block group_content %}   
        {% endblock group_content %}

        {% block post_group %}            
        {% endblock post_group %}
            
            
            
    </div>
</div>





{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}


{% block pregroup %}
 
    <div class="col-md-8">
        <div class="panel panel-default" >
            <div class="panel-body text-center">
                
                <h3 class="m0 text-bold">{{group.name}}</h3>
                <div class="mv-lg">
                    <p>{{group.description|safe}} </p>
                </div>
                <p><i> {{group.members.count}} member{{group.members.count|pluralize}}</i></p>
                <div class="text-center">
                    {% if user in group.members.all %}
    
                    <a class="btn btn-md btn-fill btn-primary" href="{% url 'groups:leave' slug=group.slug%}"><span class="glyphicon glyphicon-remove-circle"></span> Leave Group</a>
                    
                    {% else %}
                    
                    <a class="btn btn-md btn-fill btn-primary" href="{% url 'groups:join' slug=group.slug%}"><span class="glyphicon glyphicon-ok-circle"></span> Join Group</a>
                    
                    {% endif %}
                </div>
            </div>
        </div>
        <center>
        <div>
        Go to <a href="{% url 'groups:groupposts' pk=group.pk %}">  <b>Group Posts</b>  </a>
    </div>
</center>
        
    </div>

    <div class="col-md-4 pull-right" >
        <div class="panel panel-default hidden-xs hidden-sm">
            <div class="panel-heading">
                <div class="panel-title text-center">Group Members</div>
            </div>
            <div class="panel-body">
                
                {% for member in group.members.all  %}
                    
                <div class="media">
                    
                    <div class="media-body pt-sm">
                        <div class="text-bold">
                            
                            {% if member.username == request.user.username %}
                                <h4><span class="glyphicon glyphicon-user"></span><a href="{% url 'accounts:profile' pk=member %}"> You</a></h4>
                            {% else %}
                            <h4><span class="glyphicon glyphicon-user"></span><a href="{% url 'accounts:profile' pk=member %}"> {{member}}</a></h4>
                            {% endif %}
                            <div class="text-sm text-muted">
                                <i>last seen {{member.last_login | timesince}}</i> 
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div> 
            </div>


            <div>
                
                {% for a in groupmember_list  %}
                    <p>{{a}}</p>
                    
                {% endfor %}
                    
            </div>








    <!-- <div class="card" style="width: 500px;">
        <h1 class="card-title">{{group.name}}</h1>
    {% if user in group.members.all %}
 
    <a class="btn btn-lg btn-fill btn-warning" href="{% url 'groups:leave' slug=group.slug%}"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
    
    {% else %}
    
    <a class="btn btn-lg btn-fill btn-warning" href="{% url 'groups:join' slug=group.slug%}"><span class="glyphicon glyphicon-ok-circle"></span>Join</a>
    
    {% endif %}

<h2>Member Count : </h2>
</div>
</div> -->
{% endblock pregroup %}

{% block group_content %}
    <!-- <div class="col-md-8"> -->
        
        {% if group.posts.count == 0 %}
            <h1>No Posts in the Group</h1>

        {% else %}
        
            {% for post in group.posts.all  %}
                {% include 'posts/_post.html' %}
            {% endfor %}
            
        {% endif %}
            
    <!-- </div> -->

</center>
{% endblock group_content %}
    

    

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootstrap3 %}


{% block group_content %}
<h2>Create new Group</h2>
<br>
<div class="container">
    
<form action="{% url 'groups:create'%}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary btn-large" type="submit" value="Create" id="">
</form>
</div>
{% endblock group_content %}

    

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}


{% block pregroup %}
<center>
    
        <div class="container">
            
            {% if user.is_authenticated %}
            <h2>Hi!
                <a href="{% url 'accounts:profile' pk=user.username%}">@{{user.username}}</a>
                Welcome back to Groups page!
            </h2>
                
            {% endif %}
        </div>
        
        <div class="container">

            {% if user.is_authenticated %}
            <a class="btn btn-md btn-fill btn-primary" href="{% url 'groups:create' %}"><span class="glyphicon glyphicon-plus"></span> Create New Group</a>
            
        {% endif %}
    </div>  
   
<br>
</center>
{% endblock pregroup %}


{% block group_content %}
<center>
    {% for group in group_list  %}

        <div style="width: 60%;" class="list-group">                
                <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}"><h3 class="title list-group-item-heading">{{group.name}}</h3></a>
            
                
            </div>
        
    
    {% empty%}
    <p>No groups</p>

<br>
    {% endfor %}

</center>
{% endblock group_content %}