accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('profile/<pk>/', views.ProfileDetails.as_view(), name='profile')
]

api/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'


urlpatterns = [
    path('all_posts/', views.AllPosts.as_view(), name='allposts'),
    path('example/', views.Example.as_view(), name='example'),
    # path('login/', obtain_auth_token, name='login'),
    # path('user/', views.LoginView.as_view(), name='user'),
    path('jwttoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwttoken/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('xxxx/', views.LoginView.as_view(), name='xxx')

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('like/<int:pk>/', views.PostLike, name='postlike'),
    path('comment/<int:pk>/', views.PostComment, name='postcomment'),
    path('viewcomments/<int:pk>/',
         views.CommentDetails, name='commentdetails'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<pk>/', views.UserPostDetails.as_view(), name='single'),
    path('delete/<pk>', views.DeletePost.as_view(), name='delete'),
    path('comment/delete/<int:pk>/',
         views.DeleteComment.as_view(), name='deletecomment'),

]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('api/', include('api.urls', namespace='api'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Media</title>

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous" 
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous"
    />

    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"
    ></script>

    <!-- {% comment %} Fonts {% endcomment %} -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
      rel="stylesheet"
    />

    <link type="text/css" rel="stylesheet" href="{% static 'socialnetwork/css/master.css'%}"/>
  
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light mynav"  role="navigation" id='navbar'>
        
        <div class="container navbarcontainer">
            <a style="font-weight: bold;" class="navbar-brand mynav" href="{% url 'home'%}"><span class="glyphicon glyphicon-home"></span> Social Media
            </a>
            <a style="font-weight:normal;" class="navbar-brand" href="{% url 'admin:index' %}">Administration</a>
            <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav ml-auto navbar-right" >
          
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'posts:create'%}">Post</a></li>
                    <li class="nav-item"><a href="{% url 'groups:all'%}">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'groups:create'%}">Create Group</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:profile' pk=user.username %}">{{user.username}}</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:logout'%}">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'groups:all'%}">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:login'%}">Login</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:signup'%}">SignUp</a></li>
                    
                {% endif %}
                
            </ul>
          </div>
        
        </div>
    </nav>
   <div class="container">
  {% block content %}
  
      
  {% endblock content %}
  </div>
</div>


</body>


</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}

<style>
    body{
        background-image: url('C:/Users/VIKRAM/OneDrive/Pictures/Random pics/social_media.png');
    }
</style>

{% if user.is_authenticated %}
<br>


<div class="card">
    <div class="card-body">
        {% for post in post_list %}
            {% include 'posts/_post.html' %}
        {% endfor %}
        </div>
    </div>
</div>

{% else %}
<center>
    <h2>Welcome to Social Media</h2>
    <p>Please <a href="{% url 'accounts:login'%}">Login</a> to continue...</p>
    <p>No account? <a href="{% url 'accounts:signup'%}">SignUp</a></p>
    <img src="static/images/social_media.png" alt="No found" style="width:700px;height:450px";>
    
</center>

{% endif %}
    
{% endblock content %}
    

templates/thanks.html
{% extends 'base.html' %}


{% block content %}

{% if user.is_authenticated %}
<h2>You have successfully Logged out</h2>
<h3>Please visit again. Thanks</h3>
{% else %}
<h2>Thanks for visting.</h2>
<h4>Login with different account? <i><a href="{% url 'accounts:login' %}">Login</a></i></h4>
{% endif %}
    


{% endblock content %}

    