accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('profile/<pk>/', views.ProfileDetails.as_view(), name='profile')
]

api/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'


urlpatterns = [
    path('all_posts/', views.AllPosts.as_view(), name='allposts'),
    path('example/', views.Example.as_view(), name='example'),
    # path('login/', obtain_auth_token, name='login'),
    # path('user/', views.LoginView.as_view(), name='user'),
    path('jwttoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwttoken/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('xxxx/', views.LoginView.as_view(), name='xxx')

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('like/<int:pk>/', views.PostLike, name='postlike'),
    path('comment/<int:pk>/', views.PostComment, name='postcomment'),
    path('viewcomments/<int:pk>/',
         views.CommentDetails, name='commentdetails'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<pk>/', views.UserPostDetails.as_view(), name='single'),
    path('delete/<pk>', views.DeletePost.as_view(), name='delete'),
    path('comment/delete/<int:pk>/',
         views.DeleteComment.as_view(), name='deletecomment'),

]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('api/', include('api.urls', namespace='api'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.db.models.query import ValuesListIterable
from django.urls import reverse
from django.conf import settings

from groups.models import Group, GroupMember

from django.contrib.auth import get_user_model
User = get_user_model()


class PostQuerySet(models.QuerySet):
    def sorted(self):
        return self.order_by('-created_at')


class PostManager(models.Manager):
    def sorted(self):
        return self.get_queryset().sorted()  # This will call the below get_queryset()

    def get_queryset(self):
        return PostQuerySet(model=self.model, using=self._db, hints=self._hints)


class Post(models.Model):
    user = models.ForeignKey(User, related_name='userposts',
                             on_delete=models.CASCADE)
    message = models.TextField()
    image = models.ImageField(upload_to='posts/images', blank=True, default='')
    created_at = models.DateTimeField(auto_now=True)
    group = models.ForeignKey(
        Group, related_name='groupposts', on_delete=models.CASCADE)
    liked = models.ManyToManyField(User, default=None, blank=True)
    temp = models.CharField(max_length=10, null=True, blank=True)

    objects = PostManager()

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)

    @property
    def NumeberOfLikes(self):
        return self.objects.all().count()

    class Meta:
        #ordering = ['-created_at']
        unique_together = ['user', 'message']

    def get_absolute_url(self):
        return reverse('posts:single',  kwargs={'username': self.user.username, 'pk': self.pk})


'''The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name'''
Like_Choices = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)


class Like(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='liked_user')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="liked_post")
    value = models.CharField(choices=Like_Choices,
                             max_length=10, default='Like')

    def __str__(self):
        return self.user


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='commentpost', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='commented_user')
    comment = models.TextField()

    def __str__(self):
        return self.comment

posts/forms.py
from django.forms import ModelForm, fields

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

posts/views.py
from django.contrib.auth import get_user_model
from groups.models import Group, GroupMember
from django.db import models
from .forms import *
from .models import Like, Post
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, DeleteView, ListView
from django.contrib import messages

from django.http import Http404
from django.urls import reverse_lazy
from braces.views import SelectRelatedMixin

from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page

from django.core.cache import caches

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

User = get_user_model()


class PostList(SelectRelatedMixin, ListView):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        print(self.kwargs)
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UserPosts(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        print(self.request)
        self.temp = Post.objects.select_related(
            'user').filter(user__username=self.kwargs.get('username'))
        return self.temp

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.kwargs.get('username')
        return context


class UserPostDetails(LoginRequiredMixin, SelectRelatedMixin, DetailView):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        print(self.request)
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    model = Post
    fields = ('message', 'image', 'group')

    def form_valid(self, form):
        self.object = form.save(commit=False)

        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)


def GroupPosts(request, pk):
    grpposts = Post.objects.filter(group__id=pk)
    return render(request, 'posts/group_posts.html', {'groupposts': grpposts})


def PostLike(request, pk):
    user = request.user
    post = get_object_or_404(Post, pk=pk)

    if user in post.liked.all():
        post.liked.remove(user)
    else:
        post.liked.add(user)

    like, created = Like.objects.get_or_create(user=user, post_id=post.pk)

    if not created:
        if like.value == "Like":
            like.value = "Unlike"
        else:
            like.value = "Like"

    like.save()
    post.save()

    return redirect('home')


def PostComment(request, pk):
    user = request.user
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.post = post
            obj.user = user
            obj.save()

            return redirect('home')
    else:
        form = CommentForm()

    return render(request, 'posts/comment_form.html', {'form': form})


def CommentDetails(request, pk):
    post = get_object_or_404(Post, pk=pk)

    commentedpost = Post.objects.prefetch_related(
        'commentpost').get(id__exact=post.pk)

    post_comments = commentedpost.commentpost.all()

    return render(request, 'posts/post_comments.html', {'post_comments': post_comments, 'post': post})


class DeleteComment(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Comment
    select_related = ('post',)
    success_url = reverse_lazy('home')

posts/templates/posts/_post.html
<head>

</head>

<center>

    <div class="flex-container">
        
    
    <div class="card">
        <div class="card-header">
            <!-- <span class="aa"> -->
                <a style="color:brown;font-style: italic; font-size: medium;" href="{% url 'accounts:profile' pk=post.user.pk%}"><b>@{{post.user.username}}</b></h6></a>
            <!-- </span> -->
            <time class="time">
                <a style="color: brown; font-size: medium;" href="{% url 'posts:single' username=post.user.username pk=post.pk %}"><b>{{post.created_at}}</b></a>
            </time>
        </div>

        <div class="card-body">
            <h2 style="color:black;font-family:cursive; margin-bottom: 30px;">{{post.message|safe}}</h2>
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="" height="300" width="500">
            {% endif %}
        </div>

        <div class="card-footer">
            <p>
                <a style="color:rgba(0, 0, 0, 0.849); font-size:medium;font-style: italic; font-weight: lighter;" href="{% url 'groups:single' slug=post.group.slug%}"><b> Posted in {{post.group.names|default:'variable is not defined'}}</b>
                </a>    
                {% if user.is_authenticated and post.user == user and not hide_delete%}
                    <a class="btn btn-simple" title="delete" href="{% url 'posts:delete' pk=post.pk%}">
                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <span class="text-danger icon-label"><b> Delete</b></span>
                    </a>
                {% endif %}
            </p>
        </div>
    <hr style="width: 75%;background-color: whitesmoke; color: red;height: 1px;">

    <p >
    {% if user.is_authenticated %}
    

        {% if user not in post.liked.all %}
            <a class="btn btn-success btn-sm" href="{% url 'posts:postlike' pk=post.pk %}">Like</a>
        {%else%}
            <a class="btn btn-danger btn-sm" href="{% url 'posts:postlike' pk=post.pk %}">UnLike</a>
        {%endif%}
        <strong style="font-size: small;font-family: Arial, Helvetica, sans-serif;">
            {{post.liked.all.count}} like{{post.liked.all.count|pluralize}}
        </strong>

        <a class="btn btn-primary btn-sm" href="{% url 'posts:postcomment' pk=post.pk%}">Comment </a>
        <strong style="font-size: small;font-family: Arial, Helvetica, sans-serif;">
            {{post.commentpost.all.count}} comment{{post.commentpost.all.count|pluralize}}
        </strong>
        
        <a style="color:darkblue;" href="{% url 'posts:commentdetails' pk=post.pk%}"> <u>View comments</u></a>
        

        
    {%endif%}
    </p>


</div>

</div>

</center>

posts/templates/posts/comment_confirm_delete.html
{% extends 'posts/post_base.html' %}


{% block post_content %}
<h3>Are you sure you want to delete this comment?</h3>

<div class="container">
    
<form method="POST">
    {% csrf_token %}
    
    <input type="submit" class="btn btn-danger" value="Confirm">
    <a class="btn btn-simple" href="{% url 'posts:commentdetails' pk=comment.post.id %}">Cancel</a>
</form>
</div>
{% endblock post_content %}

posts/templates/posts/comment_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block post_content %}

<div class="container">
<form action="" method="POST">
    {%csrf_token%}
    {% bootstrap_form form %}
    <input class="btn btn-info btn-sm" type="submit" name="" id="" value="Comment">
</form>
</div>

<center>
    <h4><a class="btn btn-primary" href="{% url 'home'%}">back</a></h4>
</center>



{% endblock post_content %}

posts/templates/posts/group_posts.html
{% extends 'base.html' %}


{% block content %}


    <div class="col-mod-4">
        
        {% for post in groupposts  %}
        {% include 'posts/_post.html' %}
        {%empty%}
        <p>No Posts</p>
    {% endfor %}
            
    </div>


{%endblock content%}

posts/templates/posts/post_base.html
{% extends 'base.html' %}


{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            
            {% block prepost %}
                
            {% endblock prepost %}

            
            {% block post_content %}
                
            {% endblock post_content %}

            
            {% block post_post %}
                
            {% endblock post_post %}
                
                
                
        </div>
    </div>
</div>
{% endblock content %}

    

posts/templates/posts/post_comments.html
{% extends 'posts/post_base.html' %}



{% block post_content %}


<center>
    
    <h2 style="color: rgb(116, 116, 214); margin-bottom: 30px;"><i>Comments</i> on <b>{{post}}</b></h2>
</center>

<br>

<style>
hr {
    position: relative;
    width: 85%;
    top: 12px;
    border: none;
    height: 1px;
    background: black;
    margin-bottom: 10px;
}
</style>
<center>


    {% for comment in post_comments%}
    
        <div class="container">
            <div class="card bg-light">
                <div class="card-body col-md-6">
                <h3 class="card-text" style="color:brown;">  "{{comment}}"  -  <i>{{comment.user}}</i> </h3>
                </div>
                <div class="col-md-6">
                    {% if user.is_authenticated and comment.user == user %}
                     <h3><a href="{%url 'posts:deletecomment' pk=comment.id%}">  <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></a></h3>
                     {%endif%}
                </div>
                <hr>
            </div>
        </div>

    {%empty%}
        No Comments
    {%endfor%}
</center>   

<center>
    <h4><a class="btn btn-primary" href="{% url 'home'%}">back</a></h4>
</center>

{% endblock post_content %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>
<div class="posts">
     {% include 'posts/_post.html' with post=object hide_delete=True %}

     
</div>
<div class="container">
<form method="POST">
    {% csrf_token %}
    
    <input type="submit" class="btn btn-danger" value="Confirm">
    <a class="btn btn-simple" href="{% url 'posts:single' username=post.user.username pk=post.pk%}">Cancel</a>
</form>
</div>
{% endblock post_content %}
    

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}



{% block post_content %}

<center>
    <h2>Post details</h2>
    <h2>------------------------------------</h2>
</center>
    
    <div class="col-md-12">
        {% include 'posts/_post.html' %}
    </div>

{% endblock post_content %}

    

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}

{% load bootstrap3 %}


{% block post_content %}
    <h4>Create New Post</h4>

    <form method="POST" action="{% url 'posts:create' %}" id="postForm" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input class="btn btn-primary" type="submit" value="Create" id="">
    </form>
{% endblock post_content %}
    

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}


{% block post_content %}
    <div class="col-mod-4">
        
        {% for post in post_list  %}
        {% include 'posts/_post.html' %}
        {%empty%}
        <p>No Posts</p>
    {% endfor %}
            
    </div>
{% endblock post_content %}

    

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}



{% block post_content %}
<center>
<div style="margin-bottom: 20px;">
    <h1>Posts Posted by @{{post_user.username}}</h1>
</div>
</center>

<div>
    {% for post in post_list  %}
        {% include 'posts/_post.html' %}
        {%empty%}
        <p>No Posts</p>
    {% endfor %}
</div>

{% endblock post_content %}



    
    
    